services:
  fastapi_app:
    container_name: WEB_APP
    build:
      context: "."
      dockerfile: Dockerfile
    command: uvicorn app.backend.main:app --workers 1 --host 0.0.0.0 --port 5000
    ports:
      - "5000:5000"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DB_HOST: db
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: DEV_POSTGRES
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/db-files
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./config/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./logs/postgres:/var/log/postgresql

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: PUBLIC_TUNNEL
    command: tunnel --url http://fastapi_app:5000 --no-autoupdate
    restart: unless-stopped
    depends_on:
      - fastapi_app


volumes:
  postgres_data: